### PR TITLE
Fix for long text content appearing within table cells causing exception on document load

### LINKED ISSUE #152: Exception when loading document with large tag inside <td>
The attached sample fails to load in the viewer.

[ixv-long-content-issue.zip](https://github.com/Workiva/ixbrl-viewer/files/5478518/ixv-long-content-issue.zip)

The following exception is thrown when opening the viewer:

```
Uncaught (in promise) SyntaxError: Invalid regular expression: /^[^0-9A-Za-z]*INDEX\ OF\ NOTES\ TO\ FINANCIAL\ STATEMENTS\ \ Glossary\ of\ Terms\ for\ Notes1\.Significant\ Accounting\ Matters2\.New\ Accounting\ Pronouncements3\.Rate\ Matters4\.Commitments\ and\ Contingencies5\.Income\ Taxes6\.Financing\ Activities7\.Revenue\ From\ Contracts\ With\ Customers\ \ GLOSSARY\ OF\ TERMS\ FOR\ NOTES\ When\ the\ following\ terms\ and\ abbreviations\ appear\ in\ the\ text\ of\ this\ report\,\ they\ have\ the\ meanings\ indicated\ below\.\ Term\ Meaning\ \ \ AEP\ American\ Electric\ Power\ Company\,\ Inc\.\,\ an\ investor\-owned\ electric\ public\ utility\ holding\ company\ which\ includes\ American\ Electric\ Power\ Company\,\ Inc\.\ \(Parent\)\ and\ majority\ owned\ subsidiaries\ and\ affiliates\.AEP\ East\ Transmission\ \ \ \ Companies\ APTCo\,\ IMTCo\,\ KTCo\,\ OHTCo\ and\ WVTCo\.AEP\ System\ American\ Electric\ Power\ System\,\ an\ electric\ system\,\ owned\ and\ operated\ by\ AEP\ subsidiaries\.AEP\ Transmission\ Holdco\ AEP\ Transmission\ Holding\ Company\,\ LLC\,\ a\ wholly\-owned\ subsidiary\ of\ AEP\.AEPSC\ American\ Electric\ Power\ Service\ Corporation\,\ an\ AEP\ service\ subsidiary\ providing\ management\ and\ professional\ services\ to\ AEP\ and\ its\ subsidiaries\.AEPTCo\ AEP\ Transmission\ Company\,\ LLC\,\ and\ its\ consolidated\ State\ Transcos\,\ a\ subsidiary\ of\ AEP\ Transmission\ Holdco\.ALJ\ Administrative\ Law\ Judge\.APTCo\ AEP\ Appalachian\ Transmission\ Company\,\ Inc\.\,\ a\ wholly\-owned\ AEPTCo\ transmission\ subsidiary\.ASU\ Accounting\ Standards\ Update\.FASB\ Financial\ Accounting\ Standards\ Board\.FERC\ Federal\ Energy\ Regulatory\ Commission\.IMTCo\ AEP\ Indiana\ Michigan\ Transmission\ Company\,\ Inc\.\,\ a\ wholly\-owned\ AEPTCo\ transmission\ subsidiary\.IRS\ Internal\ Revenue\ Service\.KTCo\ AEP\ Kentucky\ Transmission\ Company\,\ Inc\.\,\ a\ wholly\-owned\ AEPTCo\ transmission\ subsidiary\.GLOSSARY\ OF\ TERMS\ FOR\ NOTES\ \(continued\)\ When\ the\ following\ terms\ and\ abbreviations\ appear\ in\ the\ text\ of\ this\ report\,\ they\ have\ the\ meanings\ indicated\ below\.\ Term\ Meaning\ \ \ OATT\ Open\ Access\ Transmission\ Tariff\.OHTCo\ AEP\ Ohio\ Transmission\ Company\,\ Inc\.\,\ a\ wholly\-owned\ AEPTCo\ transmission\ subsidiary\.OKTCo\ AEP\ Oklahoma\ Transmission\ Company\,\ Inc\.\,\ a\ wholly\-owned\ AEPTCo\ transmission\ subsidiary\.Parent\ American\ Electric\ Power\ Company\,\ Inc\.\,\ the\ equity\ owner\ of\ AEP\ subsidiaries\ within\ the\ AEP\ consolidation\.PJM\ Pennsylvania\ –\ New\ Jersey\ –\ Maryland\ regional\ transmission\ organization\.State\ Transcos\ Wholly\-owned\ AEPTCo\ transmission\ subsidiaries;\ APTCo\,\ IMTCo\,\ KTCo\,\ OHTCo\,\ OKTCo\,\ SWTCo\ and\ WVTCo\.SWTCo\ AEP\ Southwestern\ Transmission\ Company\,\ Inc\.\,\ a\ wholly\-owned\ AEPTCo\ transmission\ subsidiary\.Tax\ Reform\ On\ December\ 22\,\ 2017\,\ President\ Trump\ signed\ into\ law\ legislation\ referred\ to\ as\ the\ “Tax\ Cuts\ and\ Jobs\ Act”\ \(the\ TCJA\)\.\ The\ TCJA\ includes\ significant\ changes\ to\ the\ Internal\ Revenue\ Code\ of\ 1986\,\ including\ a\ reduction\ in\ the\ corporate\ federal\ income\ tax\ rate\ from\ 35%\ to\ 21%\ effective\ January\ 1\,\ 2018\.Utility\ Money\ Pool\ Centralized\ funding\ mechanism\ AEP\ uses\ to\ meet\ the\ short\-term\ cash\ requirements\ of\ certain\ utility\ subsidiaries\.Virginia\ SCC\ Virginia\ State\ Corporation\ Commission\.WVTCo\ AEP\ West\ Virginia\ Transmission\ Company\,\ Inc\.\,\ a\ wholly\-owned\ AEPTCo\ transmission\ subsidiary\.1\.\ \ \ SIGNIFICANT\ ACCOUNTING\ MATTERS\ General\ \ The\ financial\ statements\ and\ footnotes\ were\ prepared\ in\ accordance\ with\ the\ Uniform\ System\ of\ Accounts\ prescribed\ by\ the\ FERC\.\ \ The\ unaudited\ financial\ statements\ and\ footnotes\ should\ be\ read\ in\ conjunction\ with\ APTCo’s\ 2017\ FERC\ Form\ 1\ \(2017\ Annual\ Report\)\.\ In\ the\ opinion\ of\ management\,\ the\ unaudited\ interim\ financial\ statements\ reflect\ all\ normal\ and\ recurring\ accruals\ and\ adjustments\ necessary\ for\ a\ fair\ presentation\ of\ the\ net\ income\,\ financial\ position\ and\ cash\ flows\ for\ the\ interim\ periods\.\ \ Net\ income\ for\ the\ three\ months\ ended\ March\ 31\,\ 2018\ is\ not\ necessarily\ indicative\ of\ results\ that\ may\ be\ expected\ for\ the\ year\ ending\ December\ 31\,\ 2018\.\ Management\ reviewed\ subsequent\ events\ through\ May\ 22\,\ 2018\,\ the\ date\ that\ APTCo’s\ first\ quarter\ 2018\ report\ was\ issued\.\ Cash\ and\ Cash\ Equivalents\ Cash\ and\ Cash\ Equivalents\ on\ the\ statements\ of\ cash\ flows\ include\ Cash\,\ Working\ Fund\ and\ Temporary\ Cash\ Investments\ on\ the\ balance\ sheets\ with\ original\ maturities\ of\ three\ months\ or\ less\.\ \ APTCo\ invests\ excess\ cash\ through\ the\ Utility\ Money\ Pool\,\ which\ is\ recorded\ as\ Notes\ Receivable\ from\ Associated\ Companies\ on\ the\ balance\ sheets\.\ Supplementary\ Information\ \ 2018\ 2017For\ the\ Three\ Months\ viewer.js:126)
    at Viewer../src/js/viewer.js.Viewer._preProcessiXBRL (viewer.js:209)
    at Viewer../src/js/viewer.js.Viewer._preProcessiXBRL (viewer.js:209)
    at Viewer../src/js/viewer.js.Viewer._preProcessiXBRL (viewer.js:209)
    at Viewer../src/js/viewer.js.Viewer._preProcessiXBRL (viewer.js:209)
    at Viewer../src/js/viewer.js.Viewer._preProcessiXBRL (viewer.js:209)
    at Viewer../src/js/viewer.js.Viewer._preProcessiXBRL (viewer.js:209)
    at Viewer../src/js/viewer.js.Viewer._preProcessiXBRL (viewer.js:209)
    at Viewer../src/js/viewer.js.Viewer._preProcessiXBRL (viewer.js:209)
```

### PR DESCRIPTION
**Pull request by paulwarren-wk**
This PR fixes a bug whereby a very large tag appearing within a `<td>` or `<th>` element would cause the viewer to throw an exception and fail to load.

Previously we were embedding the content of the tag into a regex and checking that we had no significant characters either side of it.  This could lead to a regex that was too long for the regex engine.

This fix now manually extracts the text before and after the tag (using `indexOf` rather than a regex) and then checks that with a regex.

The document that triggered this bug is on issue #152 .

Fixes #152

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

File: iXBRLViewerPlugin/viewer/src/js/viewer.js [hunk 1]
```diff
@@ -121,9 +121,14 @@ Viewer.prototype._preProcessiXBRL = function(n, docIndex, inHidden) {
...
-                var regex = "^[^0-9A-Za-z]*" + escapeRegex($(n).text()) + "[^0-9A-Za-z]*$";
-                if (node.text().match(regex) == null) {
+            const innerText = $(n).text();
+            if (node.length == 1 && innerText.length > 0) {
+                // Use indexOf rather than a single regex because innerText may
+                // be too long for the regex engine 
+                const outerText = $(node).text();
+                const start = outerText.indexOf(innerText);
+                const wrapper = outerText.substring(0, start) + outerText.substring(start + innerText.length);
+                if (wrapper.match('[0-9A-Za-z]') !== null) {
```
Comment (brettkail-wk) [inline iXBRLViewerPlugin/viewer/src/js/viewer.js:131]: This is fine, but a few thoughts:
1. If the concern is large cells, then concatenating the before/after (or even calling `.text()`) might be unwise; perhaps we should iterate the DOM children of td/th, skipping the element when it's found.  If multiple facts can be added per cell, perhaps the answer should be cached on the td/th to avoid redundantly processing large cells.
2. I wonder if `RegExp.test` is preferable to `String.match` with a string arg, which presumably requires recompiling the pattern.

**Review by brettkail-wk — APPROVED** [review]

File: iXBRLViewerPlugin/viewer/src/js/viewer.js (hunk 1 above)
Comment (paulwarren-wk) [reply iXBRLViewerPlugin/viewer/src/js/viewer.js:131]: Regarding (1) I think there's quite a big difference between what's reasonable to search using a regex, and what it's reasonable to compile into a regex.  The string in question is around 34KB, and we have other places in the code where we handle it directly as it's the content of a tag.

(2) sounds like a reasonable improvement given that we are re-using exactly the same regex repeatedly.

Comment (brettkail-wk) [reply iXBRLViewerPlugin/viewer/src/js/viewer.js:131]: Oh, thank you for clarifying (1).  I indeed misread the code and didn't see that we were escaping+compiling the text into the regex.

**Review by sagesmith-wf — APPROVED** [review]

File: iXBRLViewerPlugin/viewer/src/js/viewer.js (hunk 1 above)
Comment (paulwarren-wk) [reply iXBRLViewerPlugin/viewer/src/js/viewer.js]: Switched to regex literal in af70b83..23388e1

File: iXBRLViewerPlugin/viewer/src/js/viewer.js [hunk 2]
```diff
@@ -128,7 +128,7 @@ Viewer.prototype._preProcessiXBRL = function(n, docIndex, inHidden) {
                 const outerText = $(node).text();
                 const start = outerText.indexOf(innerText);
                 const wrapper = outerText.substring(0, start) + outerText.substring(start + innerText.length);
-                if (wrapper.match('[0-9A-Za-z]') !== null) {
+                if (/[0-9A-Za-z]/.exec(wrapper) !== null) {
```
Comment (brettkail-wk) [inline iXBRLViewerPlugin/viewer/src/js/viewer.js]: Seems fine, but I guess `if (/[0-9A-Za-z]/.test(wrapper)) {` is preferable?

**Review by brettkail-wk — APPROVED** [review]

File: iXBRLViewerPlugin/viewer/src/js/viewer.js (hunk 2 above)
Comment (brettkail-wk) [reply iXBRLViewerPlugin/viewer/src/js/viewer.js]: Never mind, I was looking at a stale commit :-).

**Review by derekgengenbacher-wf — APPROVED** [review]

**Comment by derekgengenbacher-wf** [comment]
QA +10 Unit tests pass successfully. Builds successfully. Built and created viewer locally. Verified large text in cells does not crash viewer successfully.

@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM
